import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import LandingPage from "./LandingPage/page";
import { Toaster } from "react-hot-toast";
import AuthWatcher from "./workspace/_components/AuthWatcher";
import ChatBot from "./workspace/_components/ChatBot";
import AdminShortcutProvider from "./admin/components/AdminShortcutProvider";
import ClerkWatermarkRemover from "./workspace/_components/ClerkWatermarkRemover";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI tutor",
  description: "Generated by create next app",
};
const clearAppearance = {
  variables: {
    colorPrimary: "#22c55e",
    colorText: "#ffffff",
    colorTextSecondary: "#e5e7eb",
    colorBackground: "#1d1f2b",
    colorInputBackground: "#2a2d3c",
    colorInputText: "#ffffff",
    colorBorder: "#ffffff",
    colorInputText: "#fff",
    socialButtonsBlackButton: "#fff",
    // UserButton menu colors
    colorTextOnPrimaryBackground: "#ffffff",
    colorNeutral: "#ffffff",
    colorDanger: "#ef4444",
    // Menu item colors
    colorShimmer: "rgba(255, 255, 255, 0.1)",
    borderRadius: "0.5rem"
  },
  elements: {
    userButtonPopoverCard: {
      backgroundColor: "#161b22",
      borderColor: "#30363d",
      color: "#ffffff"
    },
    userButtonPopoverActions: {
      color: "#ffffff"
    },
    userButtonPopoverActionButton: {
      color: "#ffffff",
      "&:hover": {
        backgroundColor: "#1f2937"
      }
    },
    userButtonPopoverActionButtonText: {
      color: "#ffffff"
    },
    userButtonPopoverActionButtonIcon: {
      color: "#ffffff"
    },
    userButtonPopoverFooter: {
      display: "none",
      visibility: "hidden",
      height: "0",
      padding: "0",
      margin: "0"
    }
  }
}
export default function RootLayout({ children }) {
  return (
    <ClerkProvider  appearance={clearAppearance}>
      
      <html lang="en">
        <body
         className="overflow-x-hidden  w-full bg-black"
        >
          <AdminShortcutProvider>
         <Provider>{children}</Provider>
         </AdminShortcutProvider>
         <AuthWatcher/>
         <ChatBot/>
         <ClerkWatermarkRemover/>
        <Toaster
         position="top-right"
            toastOptions={{
              duration: 3000,
              style: {
                background: "#161B22",
                color: "#fff",
                border: "1px solid #1a1f29",
                borderRadius: "10px",
                padding: "12px 12px",
              },
            }}
        />
      </body>
    </html>
  
    </ClerkProvider>
  );
}